import subprocess
import os 
os.environ["CUDA_VISIBLE_DEVICES"] = "4"
# Defineix la comanda com una llista d'arguments
command = [
    "python", "tools/generate_detections.py",
    "--model=/home-net/ccorbi/tracking/deep_sort/weights/mars-small128.pb",
    "--mot_dir=/data-fast/data-server/ccorbi/SN-Tracking/tracking/test",
    "--output_dir=/data-fast/data-server/ccorbi/deepsort/detections"
]

# Executa la comanda
try:
    subprocess.run(command, check=True)
except subprocess.CalledProcessError as e:
    print("Error en executar la comanda:")
    print(e)


#deteccions_dir = only when generate yolo detections gt/generated by yolo